# Deep Learning
Deep learning (also known as deep structured learning, hierarchical learning or deep machine learning) is a branch of machine learning based on a set of algorithms that attempt to model high level abstractions in data. It solves this central problem in representation learning by introducing representations that are expressed in terms of others, simpler representations. Deep learning enables the computer to build complex concepts out of simpler concepts.

#### Computational Graphs

It maps inputs to the outputs where each node performs an operation. Depth is the length of the longest path from input to output but depends on the definition of what consititutes a possible computaional step. Can be a calculation level or on the model level.

In [1]:

                                                         ###################
                                                         #     Output      #
                                                         #                 #
                                                         ###################
                                                                  |
                                                                  |
#                 ###############      ###############   ###################
                  #   Output    #      #   Output    #   # Mapping from    #
                  #             #      #             #   # Features        #
                  ###############      ###############   ###################
                         |                    |                   |
                         |                    |                   |
                         |                    |                   |
###############   ###############      ###############   #####################
#   Output    #   # Mapping from#      # Mapping from#   # Additional layers # ------ Special for
#             #   # Features    #      # Features    #   # of more abstract f#         deep learning         
###############   ###############      ###############   #####################
       |                 |                    |                   |
       |                 |                    |                   |
###############   ###############      ###############   ###################
# Hand-Design #   # Hand-Design #      # Features    #   # Simple Features #
# Program     #   # Features    #      #             #   #                 #
###############   ###############      ###############   ###################
       |                 |                    |                   |
       |                 |                    |                   |
###############   ###############      ###############   ###################
#  Input      #   #  Input      #      #    Input    #   #      Input      #
###############   ###############      ###############   ###################
                                                           "Deep Learning"
"Rule-based"     "Classic Machine"     -------------------------------------
  "System"          "Learning"              "Representation Learning"

## >>>>> Mathmetic Background (2)

## [1] ----------------------------------------- Linear Algebra

#### Scalars

A scalar is just a number: 4, 15, 100

#### Vectors

A vector is an 1D array of numbers: x[i] = [12,24,61]

#### Matrices

A matrics is a 2D array of numbers: X[i,j] = [[12, 24],[31,17]]

#### Tensors

A matrics is a >2D array of numbers: X[i,j,k] = ....3D....

#### Transpose 

The transpose of a matrix is the mirror image of the matrix across a diagonal line, called main the main diagonal.
(A^T)i,j = Aj,i


#### Multiplying Matrics and Vectors

- Element-wise product

According elements in each matrixs product each other - Same shape; A*B = B*A

- Matrix product

M X N product N X D = M X D; A(B+C) = AB + AC; A(BC) = (AB)C; A*B <> B*A; (AB)^T = B^T * A^T transpose of a matrix product 

A ~ m x n, b ~ m, solve x ~ n

#### Identity Matrix / Inverse Matrix

- Matrix Inversion

A^-1 (Inversed Matrix of A)
A (Matrix of A)
In (Identity Matrix - preserve n-dimensional vectors)
A^-1 * A = In

- Normal Equation using Matrix Inversion

A * x = b
A^-1 * A * x = A^-1 * b ---> Both * A^-1
In * x = A^-1 * b ---> Transform use Inversion
x = A^-1 * b ---> Solve for x
(m need to be bigger than n)

- Identity Matrix

[1 0 0]
[0 1 0]
[0 0 1]


#### Linear Dependence and Span

**(In order to make sure A^-1 exist)

Equation - ( A * x = b ), exactly one solution for every value of 'b' | no solution for every 'b' | infinite solutions for every 'b' 

Normally, some set of vectors {v(1),v(2),v(3),...,v(n)} is given by multipying each vector v(i) by corresponding scalar coefficient and adding the result ---> The 'span' of a set of vectors is the set of all points obitained by linear combination of original vectors.

Determine whether A * x = b has a solution thus amounts to testing whether 'b' is in the 'span' of the columns of A. The particular span is known as the 'column space' or 'range' of A. 'n' >= 'm'.

- Linearly dependent

Consider 2X2 matrix has 2 identical columns which has the same column space as 2X1 matrix has the same column. The 2 columns in 2X2 matrix are linearly dependent

- Linearly independent

A set of vectors is linearly independent if no vector in the set is a linear combination of the other vectors.



#### Norms

We usually measure the size of a vector using a function called a 'norm'.

L-p Norm: SUM(|X(i)|^p)^1/p

L-2 Norm: p=2, Euclidean Norm

However, L-2 Norm increase very slowly near origin 0 (But in ML very important to identify diff between 0 and small value)

Then, use 

L-1 Norm: p=1

L-inifinite Norm: (max norn) max|X(i)|

Frobenius Norm: (Measure the size of the matrix) (alternative to L-2 Norm for vector)

"dot product of two matrixs can be rewrite in Norm"

-- X^T * Y = ||X||2 * ||Y||2 cos(theta)



#### Special Matrics and Vectors

- Diagonal Matrix

Consist mostly of zeros and have non-zero entries only along the main disgonal.

- Symmetric Matrix

A matrix that is equal to its own transpose

- Unit Vector

A  unit vector is a vector with unit Norm: ||X||2 = 1

- Orthogonal Matrix

vector X and vector Y is orthogonal, if X^T * Y = 0

A Orthogonal Matrix is a square matrix whose rows are mutually orthonormal and whose columns are mutually orthonormal


#### Eigen decomposition

Example1: integers can be decomposed into prime factors -> 12 = 2 X 2 X 3

We can also decompose matrices in ways that shows us information about their functional properties.

Matrix --> decomposation --> a set of [eigenvectors] and [eigenvalues]





#### Singular Value Decomposition

#### The Moore-Penrose Pseudoinverse


#### The Trace Operator


#### The Determinant



## [2] ----------------------------------------- Probability and Information Theory

#### Why Probability?


#### Random Variables


#### Probability Distribution

- Mass Function


- Density Function

#### Marginal Probability


#### Conditional Probability


#### The Chain Rule of Conditional Probabilities


#### Independence and Conditional Independence


#### Expectation, Variance and Covariance


#### Common Probability Distributions

- Bernoulli Distribution

- Multinoulli Distribution

- Gaussian Distribution

- Exponential Distribution

- Laplace Distribution

- Dirac Distribution

- Empirical Distribution

- Mixtures of Distribution


#### Useful Properties of Common Functions



#### Bayes' Rules



#### Technical Details of Continuous Variables


#### Information Theory


#### Kullback-Leibler (KL) divergence


#### Structured Probablistic Models






## [3] ----------------------------------------- Numerical Computation

#### Overflow and Underflow


#### Poor Conditioning


#### Gradient-Based Optimization

- Basic Concepts


- Beyond the Gradient: Jacobian and Hessian Matrices


#### Constrained Optimization


- Example: Linear Least Squares





## [4] ----------------------------------------- Machine Learning Basics


### Learning Algorithms

#### (1) The Task, T

- Classification


- Classification with missing inputs


- Regression


- Transcription


- Machine translation


- Structured output


- Anomaly detection


- Synthesis and sampling


- Imputation of missing values


- Denoising


- Density estimation or probability mass function estimation


#### (2) The performance Measure, P


#### (3) The Experience, E

- Unsupervised Learning Algorithms



- Supervised Learning Algorithms


### Capacity, Overfitting and Underfitting


- Capacity


- Overfitting


- Underfitting


- The No Free Lunch Theorem


- Regularization



### Hyperparameters and Validation Sets

- Validation Sets


- Cross Validation Sets


### Estimators, Bias and Variance

- Point Estimation


- Bias


- Variance and Standard Error


- Trading off Bias and Variance to Minimize Mean Squared Error


### Maximum Likelihood Estimation (MLE)

- Basic


- Conditional Log-Likelihood and Mean Squared Error


- Properties of Maximum Likelihood


### Bayesian Statistics

- Basic


- Maximum A Posteriori (MAP) Estimation


### Supervised Learning Algorithms

- Basic Concept


### Unsupervised Learning Algorithms

- Basic Concept


### Stochastic Gradient Descent (SGD)



### Building a Machine Learning Algorithm




# --------------------------------------------------------------------------------------------

## Challenges Motivating Deep Learning **

#### The Curse of Dimensionality


#### Local Constancy and Smoothness Regularization


#### Manifold Learning




## >>>>>> Deep Networks: Modern Practices (3)



## >>>>>> Deep Learning Research (4)

